---
- hosts: centos
  become: yes
  become_method: su
  vars:
    temp_folder: /tmp
  tasks:    
    - name: install git
      yum: name=git update_cache=yes state=latest

    # Install prerequisites    
    #- include: tasks/prerequisites.yml  
    # Install MongoDB    
    #- include: tasks/mongodb.yml    
    # Install Node.js    
    #- include: tasks/nodejs.yml
